const TODO_FETCH_START = "TODO_FETCH_START";
const TODO_FETCH_SUCCESS = "TODO_FETCH_SUCCESS";
const TODO_FETCH_ERROR = "TODO_FETCH_ERROR";
const TODO_ADD = "TODO_ADD";
const TODO_REMOVE = "TODO_REMOVE";
const TODO_TOGGLE = "TODO_TOGGLE";
const TODO_UPDATE = "TODO_UPDATE";
const TODO_PREFIX = "todo_";

export {
    TODO_FETCH_START,
    TODO_FETCH_SUCCESS,
    TODO_FETCH_ERROR,
    TODO_ADD,
    TODO_REMOVE,
    TODO_UPDATE,
    TODO_TOGGLE,
    TODO_PREFIX,
}